# Generated by Django 4.0.6 on 2023-04-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='nomi')),
                ('slug', models.SlugField(max_length=260, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Mahsulot haqida')),
                ('price', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['create_at', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
