# Generated by Django 3.2.4 on 2023-04-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
